# Это пока что только шаблон, без детальной проработки

FROM python:3.11-alpine

WORKDIR /app


# set environment variables
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1


COPY requirements.txt requirements.txt

# install dependencies
RUN pip install --no-cache-dir --upgrade pip &&\
    pip install --no-cache-dir -r requirements.txt

COPY entrypoint.sh ./entrypoint.sh

COPY . .


CMD ["python", "./main.py"]