version: '3'
services:
  redis:
    image: docker.io/bitnami/redis:7.2.1
    environment:
      - ALLOW_EMPTY_PASSWORD=yes  # для прода данный параметр удалить
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL

  elastic:
    image: elasticsearch:8.6.2
    environment:
      - "ES_JAVA_OPTS=-Xms200m -Xmx200m"
      - "discovery.type=single-node"
      - "xpack.security.enabled=false"  # для прода данный параметр удалить

  fastapi:
    build: ./src
    env_file:
      - ./fastapi.env
    depends_on:
      - elastic
      - redis

  nginx:
    image: nginx:1.19.2
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf.d:/etc/nginx/conf.d:ro

    depends_on:
      - fastapi
    ports:
      - "80:80"

volumes:
  pgdata:
