version: '3'
services:
  database:
    image: postgres
    env_file:
      - ./database.env
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  django:
    build: ./movies_admin
    env_file:
      - ./.env
    ports:
      - "8000:8000"
    depends_on:
      - database


volumes:
  pgdata:
